"""baseline — full current schema (squash of the historical migration chain)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-01 17:36:32.635198

This single migration replaces the original 10-migration chain
(940d71e4b7bf .. a1b2c3d4e5f6). That chain never built a schema from an empty
DB: its initial migration (940d71e4b7bf) was an empty stub, so `alembic upgrade
head` from base died on the first ALTER and `create_all` silently did the real
work — leaving every fresh install stamped 9 revisions behind head.

This baseline creates the entire current schema (matching models.py) so Alembic
is the single source of truth: fresh DBs upgrade base -> head cleanly and
`create_all` is no longer used at boot. Existing DBs stamped at any of the
retired revision ids are re-stamped to this baseline by db_migrate.run_migrations
(schema already present -> metadata-only stamp, no data touched).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_displays',
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('display_id')
    )
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_width', sa.Integer(), nullable=False),
    sa.Column('original_height', sa.Integer(), nullable=False),
    sa.Column('affinity_score', sa.Float(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('total_display_time', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('agent_role', sa.String(), nullable=True),
    sa.Column('creation_date', sa.String(), nullable=True),
    sa.Column('cultural_context', sa.String(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('date_display', sa.String(), nullable=True),
    sa.Column('description_narrative', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('crop_x', sa.Float(), nullable=True),
    sa.Column('crop_y', sa.Float(), nullable=True),
    sa.Column('crop_width', sa.Float(), nullable=True),
    sa.Column('crop_height', sa.Float(), nullable=True),
    sa.Column('focal_x', sa.Float(), nullable=False),
    sa.Column('focal_y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artworks_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_source_url'), ['source_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_title'), ['title'], unique=False)

    op.create_table('discovery_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('proposed_title', sa.String(), nullable=True),
    sa.Column('proposed_artist', sa.String(), nullable=True),
    sa.Column('source_api', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context_hints', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('search_session_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_queue_id'), ['id'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_time', sa.Integer(), nullable=False),
    sa.Column('default_mode', sa.String(), nullable=False),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('placard_initial_wait_sec', sa.Integer(), nullable=False),
    sa.Column('placard_initial_show_sec', sa.Integer(), nullable=False),
    sa.Column('placard_interaction_show_sec', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_name'), ['name'], unique=True)

    op.create_table('publisher_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_license', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publisher_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publisher_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publisher_collections_slug'), ['slug'], unique=True)

    op.create_table('remote_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_display', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remote_commands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remote_commands_target_display'), ['target_display'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publisher_id', sa.String(), nullable=True),
    sa.Column('publisher_name', sa.String(), nullable=True),
    sa.Column('publisher_url', sa.String(), nullable=True),
    sa.Column('trust', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cached_manifest', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_url'), ['url'], unique=True)

    op.create_table('display_playback_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('unplayed_artworks_json', sa.Text(), nullable=False),
    sa.Column('last_sequential_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('display_playback_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_display_id'), ['display_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_display_playback_sessions_playlist_id'), ['playlist_id'], unique=False)

    op.create_table('playlist_artwork',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'artwork_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_artwork')
    with op.batch_alter_table('display_playback_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_display_playback_sessions_display_id'))

    op.drop_table('display_playback_sessions')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_url'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_setting_key'))
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('remote_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remote_commands_target_display'))
        batch_op.drop_index(batch_op.f('ix_remote_commands_id'))

    op.drop_table('remote_commands')
    with op.batch_alter_table('publisher_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publisher_collections_slug'))
        batch_op.drop_index(batch_op.f('ix_publisher_collections_id'))

    op.drop_table('publisher_collections')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_name'))
        batch_op.drop_index(batch_op.f('ix_playlists_id'))

    op.drop_table('playlists')
    with op.batch_alter_table('discovery_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_queue_id'))

    op.drop_table('discovery_queue')
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artworks_title'))
        batch_op.drop_index(batch_op.f('ix_artworks_status'))
        batch_op.drop_index(batch_op.f('ix_artworks_source_url'))
        batch_op.drop_index(batch_op.f('ix_artworks_id'))
        batch_op.drop_index(batch_op.f('ix_artworks_filename'))
        batch_op.drop_index(batch_op.f('ix_artworks_agent_name'))

    op.drop_table('artworks')
    op.drop_table('active_displays')
    # ### end Alembic commands ###
