"""
Curation spec for the offline catalog builder.

Philosophy (Josh's standard): **curate the canon first, then resolve to a verified public-domain
image** — start from an opinionated "top works of all time" list, not from whatever an API search
returns. Each collection lists explicit `picks` (the must-see canon); the builder resolves each to a
PD image via the best source and verifies it's a real display image. Some famous works are still
under copyright and simply won't resolve to a PD source — that's expected; they're logged as MISSING.

Per-collection keys:
  - picks: [{title, artist?, sources?}]   the curated canon (resolved + verified)
  - pick_sources: resolver order for picks (default ["wikimedia", "museums"])
  - sources: museum ids for the resolver + query supplement; "nasa"/"loc" for those fetchers
  - queries / query_supplement: optional discovery to top up painting collections (default on);
    turned OFF for collections where loose queries pulled junk (botanical/sculpture/cosmos/...).
  - target: cap on items.

Resolver ids: museum ids "chicago"/"met"/"cleveland"/"rijks"/"smk", plus "wikimedia", "nasa".
Modern rock/film/band posters and most 20th-c works remain copyrighted and are intentionally absent.
"""

COLLECTIONS = [
    {
        "id": "impressionism",
        "title": "Impressionism",
        "description": "Light, color, and fleeting moments from the movement that broke with the academy.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Claude Monet", "Pierre-Auguste Renoir", "Edgar Degas", "Camille Pissarro"],
        "target": 24,
        "picks": [
            {"title": "Impression, Sunrise", "artist": "Claude Monet"},
            {"title": "Water Lilies", "artist": "Claude Monet"},
            {"title": "Woman with a Parasol", "artist": "Claude Monet"},
            {"title": "Dance at Le Moulin de la Galette", "artist": "Pierre-Auguste Renoir"},
            {"title": "Luncheon of the Boating Party", "artist": "Pierre-Auguste Renoir"},
            {"title": "The Ballet Class", "artist": "Edgar Degas"},
            {"title": "L'Absinthe", "artist": "Edgar Degas"},
            {"title": "Boulevard Montmartre", "artist": "Camille Pissarro"},
            {"title": "A Bar at the Folies-Bergère", "artist": "Édouard Manet"},
            {"title": "The Cradle", "artist": "Berthe Morisot"},
        ],
    },
    {
        "id": "post-impressionism",
        "title": "Post-Impressionism",
        "description": "Bold color and expressive form — the bridge from Impressionism to modern art.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "rijks"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Vincent van Gogh", "Paul Cezanne", "Georges Seurat"],
        "target": 24,
        "picks": [
            {"title": "The Starry Night", "artist": "Vincent van Gogh"},
            {"title": "Sunflowers", "artist": "Vincent van Gogh"},
            {"title": "Café Terrace at Night", "artist": "Vincent van Gogh"},
            {"title": "The Bedroom", "artist": "Vincent van Gogh"},
            {"title": "The Card Players", "artist": "Paul Cézanne"},
            {"title": "Mont Sainte-Victoire", "artist": "Paul Cézanne"},
            {"title": "Where Do We Come From? What Are We? Where Are We Going?", "artist": "Paul Gauguin"},
            {"title": "Vision after the Sermon", "artist": "Paul Gauguin"},
            {"title": "A Sunday on La Grande Jatte", "artist": "Georges Seurat"},
            {"title": "At the Moulin Rouge", "artist": "Henri de Toulouse-Lautrec"},
        ],
    },
    {
        "id": "dutch-golden-age",
        "title": "The Dutch Golden Age",
        "description": "Light, intimacy, and virtuosity from the 17th-century Netherlands.",
        "license": "Public Domain",
        "sources": ["rijks", "met"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Rembrandt van Rijn", "Johannes Vermeer", "Frans Hals"],
        "target": 20,
        "picks": [
            {"title": "The Night Watch", "artist": "Rembrandt van Rijn"},
            {"title": "The Anatomy Lesson of Dr. Nicolaes Tulp", "artist": "Rembrandt van Rijn"},
            {"title": "Self-Portrait with Two Circles", "artist": "Rembrandt van Rijn"},
            {"title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer"},
            {"title": "The Milkmaid", "artist": "Johannes Vermeer"},
            {"title": "View of Delft", "artist": "Johannes Vermeer"},
            {"title": "The Laughing Cavalier", "artist": "Frans Hals"},
            {"title": "The Merry Drinker", "artist": "Frans Hals"},
        ],
    },
    {
        "id": "renaissance",
        "title": "The Italian Renaissance",
        "description": "Harmony, perspective, and humanism from the rebirth of classical ideals.",
        "license": "Public Domain",
        "sources": ["met", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Sandro Botticelli", "Titian", "Renaissance Italian painting"],
        "target": 20,
        "picks": [
            {"title": "Mona Lisa", "artist": "Leonardo da Vinci"},
            {"title": "The Last Supper", "artist": "Leonardo da Vinci"},
            {"title": "The Birth of Venus", "artist": "Sandro Botticelli"},
            {"title": "Primavera", "artist": "Sandro Botticelli"},
            {"title": "The School of Athens", "artist": "Raphael"},
            {"title": "Sistine Madonna", "artist": "Raphael"},
            {"title": "The Creation of Adam", "artist": "Michelangelo"},
            {"title": "Venus of Urbino", "artist": "Titian"},
            {"title": "The Tribute Money", "artist": "Masaccio"},
        ],
    },
    {
        "id": "ukiyo-e",
        "title": "Japanese Ukiyo-e",
        "description": "Woodblock prints of the 'floating world' — landscapes, kabuki, and everyday Edo life.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "smk"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Katsushika Hokusai", "Utagawa Hiroshige", "Kitagawa Utamaro"],
        "target": 22,
        "picks": [
            {"title": "The Great Wave off Kanagawa", "artist": "Katsushika Hokusai"},
            {"title": "Fine Wind, Clear Morning", "artist": "Katsushika Hokusai"},
            {"title": "Kajikazawa in Kai Province", "artist": "Katsushika Hokusai"},
            {"title": "Plum Park in Kameido", "artist": "Utagawa Hiroshige"},
            {"title": "Sudden Shower over Shin-Ōhashi Bridge and Atake", "artist": "Utagawa Hiroshige"},
            {"title": "Three Beauties of the Present Day", "artist": "Kitagawa Utamaro"},
            {"title": "The Actor Otani Oniji III", "artist": "Tōshūsai Sharaku"},
        ],
    },
    {
        "id": "romanticism",
        "title": "Romanticism & the Sublime",
        "description": "Nature at its most awe-inspiring, and the human drama set against it.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Thomas Cole", "J. M. W. Turner"],
        "target": 20,
        "picks": [
            {"title": "Wanderer above the Sea of Fog", "artist": "Caspar David Friedrich"},
            {"title": "The Sea of Ice", "artist": "Caspar David Friedrich"},
            {"title": "Liberty Leading the People", "artist": "Eugène Delacroix"},
            {"title": "The Raft of the Medusa", "artist": "Théodore Géricault"},
            {"title": "The Fighting Temeraire", "artist": "J. M. W. Turner"},
            {"title": "Rain, Steam and Speed", "artist": "J. M. W. Turner"},
            {"title": "The Hay Wain", "artist": "John Constable"},
            {"title": "The Oxbow", "artist": "Thomas Cole"},
            {"title": "The Third of May 1808", "artist": "Francisco Goya"},
            {"title": "Saturn Devouring His Son", "artist": "Francisco Goya"},
        ],
    },
    {
        "id": "american-art",
        "title": "American Art",
        "description": "From frontier light to mid-century city scenes — the American eye.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Winslow Homer", "John Singer Sargent"],
        "target": 20,
        "picks": [
            {"title": "Nighthawks", "artist": "Edward Hopper"},
            {"title": "American Gothic", "artist": "Grant Wood"},
            {"title": "Arrangement in Grey and Black No. 1", "artist": "James McNeill Whistler"},
            {"title": "Washington Crossing the Delaware", "artist": "Emanuel Leutze"},
            {"title": "The Gulf Stream", "artist": "Winslow Homer"},
            {"title": "Snap the Whip", "artist": "Winslow Homer"},
            {"title": "Madame X", "artist": "John Singer Sargent"},
            {"title": "The Daughters of Edward Darley Boit", "artist": "John Singer Sargent"},
        ],
    },
    {
        "id": "portraits",
        "title": "Portraits Through Time",
        "description": "Faces that have held our gaze across the centuries.",
        "license": "Public Domain",
        "sources": ["met", "rijks", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["portrait painting"],
        "target": 16,
        "picks": [
            {"title": "The Arnolfini Portrait", "artist": "Jan van Eyck"},
            {"title": "Las Meninas", "artist": "Diego Velázquez"},
            {"title": "Portrait of Pope Innocent X", "artist": "Diego Velázquez"},
            {"title": "The Blue Boy", "artist": "Thomas Gainsborough"},
            {"title": "Napoleon Crossing the Alps", "artist": "Jacques-Louis David"},
            {"title": "Self-Portrait at Twenty-Eight", "artist": "Albrecht Dürer"},
            {"title": "Portrait of Dr. Gachet", "artist": "Vincent van Gogh"},
            {"title": "Portrait of Madame Récamier", "artist": "Jacques-Louis David"},
            {"title": "Lady with an Ermine", "artist": "Leonardo da Vinci"},
        ],
    },
    {
        "id": "still-life",
        "title": "Still Life & Flowers",
        "description": "Quiet arrangements of fruit, flowers, and objects — beauty in the everyday.",
        "license": "Public Domain",
        "sources": ["rijks", "met", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["still life flowers", "vanitas"],
        "target": 18,
        "picks": [
            {"title": "Irises", "artist": "Vincent van Gogh"},
            {"title": "The Basket of Apples", "artist": "Paul Cézanne"},
            {"title": "Still Life with Flowers in a Glass Vase", "artist": "Jan Davidsz. de Heem"},
            {"title": "Vase with Twelve Sunflowers", "artist": "Vincent van Gogh"},
            {"title": "Sunflowers", "artist": "Vincent van Gogh"},
            {"title": "Flowers in a Wooden Vessel", "artist": "Jan Brueghel the Elder"},
            {"title": "A Vase of Flowers", "artist": "Rachel Ruysch"},
        ],
    },
    {
        "id": "sculpture-antiquity",
        "title": "Sculpture & Antiquity",
        "description": "Marble, bronze, and stone — the enduring forms of the ancient and classical world.",
        "license": "Public Domain",
        "sources": ["met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["marble sculpture", "Greek statue"],
        "target": 16,
        "picks": [
            {"title": "Venus de Milo", "artist": "Ancient Greek"},
            {"title": "Winged Victory of Samothrace", "artist": "Ancient Greek"},
            {"title": "Laocoön and His Sons", "artist": "Ancient Greek"},
            {"title": "David", "artist": "Michelangelo"},
            {"title": "Pietà", "artist": "Michelangelo"},
            {"title": "Discobolus", "artist": "Myron"},
            {"title": "Bust of Nefertiti", "artist": "Thutmose"},
            {"title": "The Thinker", "artist": "Auguste Rodin"},
            {"title": "Augustus of Prima Porta", "artist": "Ancient Roman"},
        ],
    },
    {
        "id": "botanical",
        "title": "Birds & Botanicals",
        "description": "The art of scientific observation — Audubon's birds and the great botanical plates.",
        "license": "Public Domain",
        "sources": ["chicago", "met"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["John James Audubon"],
        "target": 16,
        "picks": [
            {"title": "American Flamingo", "artist": "John James Audubon"},
            {"title": "Wild Turkey", "artist": "John James Audubon"},
            {"title": "Snowy Owl", "artist": "John James Audubon"},
            {"title": "Carolina Parakeet", "artist": "John James Audubon"},
            {"title": "Whooping Crane", "artist": "John James Audubon"},
            {"title": "Great Blue Heron", "artist": "John James Audubon"},
            {"title": "Roseate Spoonbill", "artist": "John James Audubon"},
            {"title": "Rosa centifolia", "artist": "Pierre-Joseph Redouté"},
            {"title": "Strelitzia reginae", "artist": "Pierre-Joseph Redouté"},
        ],
    },
    {
        "id": "cosmos",
        "title": "The Cosmos",
        "description": "Public-domain views of deep space from Hubble and the James Webb Space Telescope.",
        "license": "Public Domain (NASA / ESA)",
        "sources": ["nasa"],
        "pick_sources": ["wikimedia", "nasa"],
        "queries": [],
        "query_supplement": False,
        "target": 16,
        "picks": [
            {"title": "Pillars of Creation"},
            {"title": "Webb's First Deep Field"},
            {"title": "Cosmic Cliffs Carina Nebula"},
            {"title": "Hubble Ultra Deep Field"},
            {"title": "Sombrero Galaxy"},
            {"title": "Whirlpool Galaxy"},
            {"title": "Crab Nebula"},
            {"title": "Horsehead Nebula"},
            {"title": "Andromeda Galaxy"},
            {"title": "Veil Nebula"},
            {"title": "Southern Ring Nebula Webb"},
            {"title": "Stephan's Quintet Webb"},
        ],
    },
    {
        "id": "earth-and-spaceflight",
        "title": "Earth & Spaceflight",
        "description": "Our planet and the missions that let us see it — from Apollo to deep space.",
        "license": "Public Domain (NASA)",
        "sources": ["nasa"],
        "pick_sources": ["wikimedia", "nasa"],
        "queries": [],
        "query_supplement": False,
        "target": 12,
        "picks": [
            {"title": "The Blue Marble"},
            {"title": "Earthrise"},
            {"title": "Pale Blue Dot"},
            {"title": "Buzz Aldrin on the Moon Apollo 11"},
            {"title": "Bruce McCandless spacewalk"},
            {"title": "Saturn from Cassini"},
            {"title": "The Earth seen from Apollo 17"},
            {"title": "Apollo 11 bootprint on the Moon"},
        ],
    },
    {
        "id": "vintage-posters",
        "title": "Vintage Posters & Graphic Design",
        "description": "Public-domain poster art — Art Nouveau, Belle Époque, and golden-age travel design.",
        "license": "Public Domain",
        "sources": ["loc", "wikimedia"],
        "pick_sources": ["wikimedia"],
        "queries": ["travel poster", "WPA poster"],
        "target": 20,
        "picks": [
            {"title": "Moulin Rouge: La Goulue", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Divan Japonais", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Aristide Bruant dans son cabaret", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Jane Avril", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Gismonda", "artist": "Alphonse Mucha"},
            {"title": "Job", "artist": "Alphonse Mucha"},
            {"title": "Bières de la Meuse", "artist": "Alphonse Mucha"},
            {"title": "F. Champenois Imprimeur-Éditeur", "artist": "Alphonse Mucha"},
            {"title": "Le Chat Noir", "artist": "Théophile Steinlen"},
            {"title": "Folies Bergère", "artist": "Jules Chéret"},
        ],
    },
    {
        "id": "documentary-photography",
        "title": "Documentary Photography",
        "description": "The unflinching photograph — the FSA archive and the pioneers of the form.",
        "license": "Public Domain",
        "sources": ["loc", "wikimedia"],
        "pick_sources": ["wikimedia"],
        "queries": ["Farm Security Administration photograph", "Dorothea Lange"],
        "target": 16,
        "picks": [
            {"title": "Migrant Mother", "artist": "Dorothea Lange"},
            {"title": "The Steerage", "artist": "Alfred Stieglitz"},
            {"title": "Power house mechanic working on steam pump", "artist": "Lewis Hine"},
            {"title": "The Horse in Motion", "artist": "Eadweard Muybridge"},
            {"title": "Pomp and Circumstance Abraham Lincoln portrait", "artist": "Mathew Brady"},
            {"title": "Allie Mae Burroughs", "artist": "Walker Evans"},
            {"title": "View from the Window at Le Gras", "artist": "Nicéphore Niépce"},
        ],
    },
    {
        "id": "modern-masters",
        "title": "Modern Masters",
        "description": "The turn into modernism — symbolism and expression at the dawn of the new century.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "smk"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Gustav Klimt", "Edvard Munch"],
        "target": 14,
        "picks": [
            {"title": "The Kiss", "artist": "Gustav Klimt"},
            {"title": "Portrait of Adele Bloch-Bauer I", "artist": "Gustav Klimt"},
            {"title": "Death and Life", "artist": "Gustav Klimt"},
            {"title": "The Scream", "artist": "Edvard Munch"},
            {"title": "Madonna", "artist": "Edvard Munch"},
            {"title": "The Sick Child", "artist": "Edvard Munch"},
            {"title": "The Dance of Life", "artist": "Edvard Munch"},
            {"title": "Seated Woman with Bent Knee", "artist": "Egon Schiele"},
        ],
    },
]


def get_collection(collection_id: str):
    return next((c for c in COLLECTIONS if c["id"] == collection_id), None)
